import { launch, page, go, ADMIN, USER, hscroll } from './lib.mjs';
const errs = []; const b = await launch(); const log = (...a) => console.log(...a);
const a = await page(b, ADMIN, 1440, 900, errs);
await go(a, 'cases');
await a.click('.case-new > summary');
await a.selectOption('#case-form select[name="defendant"]', { label: 'Агент (юзер)' });
await a.fill('#case-form textarea[name="charge"]', 'Тест T2.12: назвал Междумосковье деревней');
await a.click('#case-form button[type="submit"]'); await a.waitForTimeout(1500);
log('нет улики → осталась форма:', await a.isVisible('#case-form'));
await a.check('#case-form input[name="ev"] >> nth=0');
await a.click('#case-form button[type="submit"]'); await a.waitForTimeout(3500);
log('карточка:', (await a.textContent('.case-card .case-top')).trim());
await a.screenshot({ path: '/data/work/c1-admin-open.png', fullPage: true });
await a.click('.case-card [data-act="warrant-yes"]'); await a.waitForTimeout(3500);
log('после ордера:', (await a.textContent('.case-card .case-stamp')).trim());
const u = await page(b, USER, 390, 844, errs);
log('метка у «Дела»:', await u.$eval('.nav-link[data-section="cases"]', x => x.classList.contains('has-alert')));
log('уведомление:', await u.$$eval('.notification', n => n.map(x => x.textContent.trim()).join(' / ')));
await go(u, 'cases');
await u.screenshot({ path: '/data/work/c1-user-knock-390.png', fullPage: true });
await u.click('.case-card [data-act="door-docs"]'); await u.waitForTimeout(3500);
log('после документов:', (await u.textContent('.case-card .case-stamp')).trim(), '|', (await u.textContent('.case-card .case-verdict')).trim());
log('вбок 390:', await hscroll(u));
await u.screenshot({ path: '/data/work/c1-user-invalid-390.png', fullPage: true });
log('ERRORS:', errs.join('\n') || 'нет');
await b.close(); process.exit(0);
