import { launch, page, go, ADMIN, USER, hscroll } from './lib.mjs';
const errs = []; const b = await launch(); const log = (...a) => console.log(...a);
const a = await page(b, ADMIN, 1440, 900, errs);
await go(a, 'cases');
await a.click('.case-new > summary');
await a.selectOption('#case-form select[name="defendant"]', { label: 'Агент (юзер)' });
await a.fill('#case-form textarea[name="charge"]', 'Тест T2.12: сказал «пикаповый» вместо «пиковый»');
await a.check('#case-form input[name="ev"] >> nth=0');
await a.click('#case-form button[type="submit"]'); await a.waitForTimeout(3500);
await a.click('.case-list .case-card >> nth=0 >> [data-act="warrant-yes"]'); await a.waitForTimeout(3500);
const u = await page(b, USER, 390, 844, errs);
await go(u, 'cases');
await u.click('.case-card [data-act="door-docs"]'); await u.waitForTimeout(3500);
log('удостоверение показано:', await u.isVisible('.case-knock .cred-card'), '|', (await u.textContent('.case-knock .case-ok')).trim());
await u.screenshot({ path: '/data/work/c2-user-cred-390.png', fullPage: true });
u.once('dialog', d => d.accept());
await u.click('.case-card [data-act="door-resist"]'); await u.waitForTimeout(3500);
log('после «Не открывать»:', (await u.textContent('.case-card .case-stamp')).trim(), '| штамп:', await u.isVisible('.case-resist'));
await u.fill('.case-defense textarea', 'Это был не я, это KENTA$$');
await u.click('.case-defense button'); await u.waitForTimeout(3500);
log('ответ записан:', await u.isVisible('.case-defense-text'), '| форма ответа исчезла:', !(await u.isVisible('.case-defense')));
log('ответчик не голосует:', !(await u.isVisible('.case-card [data-act="vote"]')));
await go(a, 'cases');
await a.fill('.case-admin input[name="hours"]', '1');
a.once('dialog', d => d.accept());
await a.click('.case-card [data-act="verdict-guilty"]'); await a.waitForTimeout(3500);
log('приговор:', (await a.textContent('.case-card .case-verdict')).trim());
await a.screenshot({ path: '/data/work/c2-admin-verdict.png', fullPage: true });
// ответчик под арестом: чат
await u.reload({ waitUntil: 'networkidle' }); await u.waitForTimeout(3000);
await go(u, 'chat');
log('вкладки:', await u.isVisible('#chat-tabs'), '| выбрана:', await u.$eval('#chat-tabs [aria-selected="true"]', x => x.textContent), '| арест:', (await u.textContent('#chat-jail')).trim().slice(0, 40));
await u.fill('#chat-message-text', 'Тест T2.12: привет из камеры'); await u.click('#form-chat-message button[type="submit"]'); await u.waitForTimeout(3500);
log('в камере видно сообщение:', await u.isVisible('text=привет из камеры'));
await u.screenshot({ path: '/data/work/c2-user-cell-390.png', fullPage: true });
await u.click('#chat-tabs [data-ch="general"]'); await u.waitForTimeout(3000);
log('общий: ввод закрыт:', await u.$eval('#chat-message-text', x => x.disabled), '| нет камерного:', !(await u.isVisible('text=привет из камеры')));
await go(u, 'profile');
log('штамп в профиле:', (await u.textContent('.jail-chip')).trim());
log('вбок 390:', await hscroll(u));
// админ видит камеру, отменяет дело
await go(a, 'chat');
await a.click('#chat-tabs [data-ch="cell"]'); await a.waitForTimeout(3000);
log('админ видит камеру:', await a.isVisible('text=привет из камеры'));
await go(a, 'cases');
a.once('dialog', d => d.accept());
await a.click('.case-card [data-act="cancel"]'); await a.waitForTimeout(3500);
log('после отмены:', (await a.textContent('.case-card .case-stamp')).trim());
await u.reload({ waitUntil: 'networkidle' }); await u.waitForTimeout(3000);
await go(u, 'chat');
log('после отмены вкладок нет:', !(await u.isVisible('#chat-tabs')), '| ввод открыт:', !(await u.$eval('#chat-message-text', x => x.disabled)));
await go(u, 'cases');
await u.screenshot({ path: '/data/work/c2-user-archive-390.png', fullPage: true });
const a2 = await page(b, USER, 1440, 900, errs); await go(a2, 'cases');
await a2.screenshot({ path: '/data/work/c2-user-archive-1440.png', fullPage: true });
log('вбок 1440:', await hscroll(a2));
log('ERRORS:', errs.join('\n') || 'нет');
await b.close(); process.exit(0);
