import { launch, page, go, hscroll, token, ADMIN, USER } from './lib.mjs';
import fs from 'fs';
const cfg = fs.readFileSync('/data/repo/js/config.js', 'utf8');
const KEY = cfg.match(/eyJ[\w-]+\.[\w-]+\.[\w-]+|sb_publishable_[\w-]+/)[0];
const U = 'https://dgfsxsargqypvwiifyrp.supabase.co';
async function rpc(email, fn, args) {
  const t = (await token(email)).access_token;
  const r = await fetch(`${U}/rest/v1/rpc/${fn}`, { method: 'POST', headers: { apikey: KEY, authorization: 'Bearer ' + t, 'content-type': 'application/json' }, body: JSON.stringify(args) });
  return [r.status, await r.text()];
}
const log = (...a) => console.log(...a);
const errs = [];
const [s1, fid] = await rpc(ADMIN, 'save_faction', { p_id: null, p_name: 'Тест-фракция', p_motto: 'тест', p_color: '#335577' });
log('save_faction', s1, fid);
fs.writeFileSync('/data/work/t213-fid', String(fid));
log('join', ...(await rpc(USER, 'join_faction', { p_faction: Number(fid) })));
const b = await launch();
const u = await page(b, USER, 1440, 900, errs); await go(u, 'chat');
const a = await page(b, ADMIN, 1440, 900, errs); await go(a, 'chat');
log('user tabs:', await u.$$eval('#chat-tabs button', bs => bs.map(x => x.textContent + (x.getAttribute('aria-selected') === 'true' ? '*' : ''))), 'hidden', await u.$eval('#chat-tabs', e => e.hidden));
log('admin tabs:', await a.$$eval('#chat-tabs button', bs => bs.map(x => x.textContent)));
await u.fill('#chat-message-text', 'Тест T2.13 @Агент (админ) см. https://example.com/x');
await u.click('#form-chat-message button[type=submit]');
log('send disabled right after:', await u.$eval('#form-chat-message button[type=submit]', b => b.disabled));
await u.waitForTimeout(2500);
log('admin sees mention:', await a.$$eval('.chat-message.mentions-me', l => l.length), 'mention-b:', await a.$$eval('.chat-mention', l => l.length), 'link:', await a.$$eval('.chat-message-text a[href^="https://example.com"]', l => l.length));
const last = a.locator('.chat-message:not(.system)').last();
await last.locator('.chat-react[data-react=like]').click(); await a.waitForTimeout(1500);
log('like active:', await a.locator('.chat-message:not(.system)').last().locator('.chat-react.active').count());
await a.locator('.chat-message:not(.system)').last().locator('.chat-reply-btn').click();
log('reply bar:', await a.$eval('#chat-reply-bar', e => e.textContent.trim().slice(0, 60)));
await a.fill('#chat-message-text', 'Ответ админа'); await a.click('#form-chat-message button[type=submit]'); await a.waitForTimeout(2500);
log('reply ref in user view:', await u.$$eval('.chat-reply-ref', l => l.map(x => x.textContent.trim().slice(0, 50))));
log('reply bar gone:', await a.$$eval('#chat-reply-bar', l => l.length));
await u.click(`#chat-tabs [data-ch="faction:${fid}"]`); await u.waitForTimeout(2000);
await u.fill('#chat-message-text', 'Сообщение фракции'); await u.click('#form-chat-message button[type=submit]'); await u.waitForTimeout(2500);
log('faction msgs user:', await u.$$eval('.chat-message-text', l => l.map(x => x.textContent)));
await a.click(`#chat-tabs [data-ch="faction:${fid}"]`); await a.waitForTimeout(2000);
log('faction msgs admin:', await a.$$eval('.chat-message-text', l => l.map(x => x.textContent)));
await u.click('#chat-tabs [data-ch="general"]'); await u.waitForTimeout(2000);
await u.evaluate(async () => { const ui = await import('./js/ui.js'); ui.renderChatMessages([{ id: 1, kind: 'system', message_text: 'Открыто дело № 1', created_at: new Date().toISOString(), card: { type: 'case' } }, { id: 2, kind: 'system', message_text: 'Событие дня: «…»', created_at: new Date().toISOString(), card: { type: 'event', event_id: 1 } }], 'x', 'user', () => {}, null, { onSystem: (k) => window.__sys = k }); document.querySelector('.chat-sys-act').click(); });
log('system:', await u.$$eval('.chat-message.system .chat-sys-label', l => l.length), 'click ->', await u.evaluate(() => window.__sys));
await u.screenshot({ path: '/data/work/t213-sys.png' });
await a.click('#chat-tabs [data-ch="general"]'); await a.waitForTimeout(2000);
await a.screenshot({ path: '/data/work/t213-admin-1440.png' });
log('mute', ...(await rpc(ADMIN, 'mute_user', { p_user: '1ba20aa6-e054-4eb5-b303-8a9488659de0', p_minutes: 5, p_reason: 'тест' })));
await go(u, 'home'); await go(u, 'chat');
log('mute banner:', await u.$eval('#chat-jail', e => !e.hidden && e.textContent), 'input disabled', await u.$eval('#chat-message-text', e => e.disabled));
log('unmute', ...(await rpc(ADMIN, 'mute_user', { p_user: '1ba20aa6-e054-4eb5-b303-8a9488659de0', p_minutes: 0, p_reason: null })));
const m = await page(b, USER, 390, 844, errs); await go(m, 'chat');
log('390 hscroll:', await hscroll(m));
await m.locator('.chat-message:not(.system) .chat-reply-btn').last().click();
await m.screenshot({ path: '/data/work/t213-390.png' });
log('home event of day:', await m.evaluate(async () => { document.querySelector('.nav-link[data-section="home"]')?.click(); await new Promise(r => setTimeout(r, 2500)); const el = document.getElementById('vadim-of-day'); return el && el.style.display + ' ' + el.textContent.slice(0, 60); }));
log('errors:', errs.filter(e => !/future|JWT/.test(e)));
await b.close(); process.exit(0);